/* eslint-disable react/no-unescaped-entities */
import Link from "next/link";
import "../globals.css";
import { Inter } from "next/font/google";
import { getPages } from "@/sanity/sanity-utils";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "My Portfolio Site",
  description: "Generated by Next + sanity",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  //get all of our pages
  const pages = await getPages();

  return (
    <html lang="en">
      <body className="max-w-3xl mx-auto py-3 ">
        <header className="flex items-center justify-between border-b-2 rounded-b-lg">
          <Link
            href="/"
            className="bg-gradient-to-t from-text-300 via-sky-500 to-transparent bg-clip-text text-transparent text-3xl font-bold"
          >
            My Portfolio
          </Link>
          <div
            className="flex items-center gap-3
         text-md text-sky-600"
          >
            {pages.map((page) => (
              <Link
                key={page._id}
                href={`/${page.slug}`}
                className="hover:underline"
              >
                {page.title}
              </Link>
            ))}
          </div>
        </header>
        <main className="py-20">{children}</main>
      </body>
    </html>
  );
}
